In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0, 11)

In [13]:
sliceOfArray = arr[0:5]

In [14]:
sliceOfArray

array([0, 1, 2, 3, 4])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
sliceOfArray[:] = 99

In [18]:
sliceOfArray

array([99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [20]:
arrCopy = arr.copy()

In [21]:
arrCopy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arrCopy[:] = 100


In [23]:
arrCopy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr2D = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [25]:
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr2D.shape

(3, 3)

In [27]:
arr2D[0]

array([ 5, 10, 15])

In [28]:
arr2D[2]

array([35, 40, 45])

In [29]:
arr2D[1][1]

25

In [30]:
arr2D[1,1]

25

In [31]:
arr2D[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [32]:
arr2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
arr = np.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
arr >= 4

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [37]:
boolArr = arr > 4

In [38]:
boolArr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
arr[boolArr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[arr >= 4]

array([ 4,  5,  6,  7,  8,  9, 10])