In [5]:
import numpy as np

In [6]:
myList = [1, 2, 3]

In [7]:
type(myList)

list

In [8]:
np.array(myList)

array([1, 2, 3])

In [9]:
myArr = np.array(myList)

In [10]:
type(myArr)

numpy.ndarray

In [11]:
myMatrix = [[1,2,3], [4,5,6], [7,8,9]]

In [12]:
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((4))

array([1., 1., 1., 1.])

In [28]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
len(np.linspace(0,10,11))

11

In [30]:
np.eye(5)    #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.random.rand(5,2)

array([[0.19274605, 0.04861226],
       [0.57240095, 0.09195666],
       [0.50339882, 0.69332806],
       [0.12993462, 0.13914067],
       [0.23292112, 0.47565498]])

In [38]:
np.random.randn(10)

array([ 1.32793371,  1.83131265, -0.35148864, -1.80381283, -0.08308203,
        0.23186646,  0.52888965, -0.74734254,  0.30925759,  0.12113392])

In [39]:
np.random.randn(2,3)

array([[-1.64118358, -1.12634668, -0.59279737],
       [ 0.72785476, -0.65545965, -1.47929734]])

In [41]:
np.random.randint(0, 101, (4,5))

array([[91, 24, 77, 77, 82],
       [33, 71, 98, 52, 62],
       [80, 78, 22,  1, 41],
       [ 5, 55,  1, 89, 16]])

In [42]:
np.random.randint(0,101)

89

In [43]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [47]:
arr = np.arange(0,25)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranArr = np.random.randint(0, 101, 10)

In [51]:
ranArr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [52]:
ranArr.max()

99

In [53]:
ranArr.min()

2

In [54]:
ranArr.argmax()

5

In [55]:
ranArr.argmin()

7

In [61]:
ranArr.dtype

dtype('int32')

In [57]:
arr.shape

(25,)

In [58]:
arr = arr.reshape(5,5)

In [59]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr.shape

(5, 5)